FROM golang:1.22 AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY cmd/serviceB ./cmd/serviceB
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /serviceB ./cmd/serviceB

FROM gcr.io/distroless/base-debian12
WORKDIR /app
COPY --from=builder /serviceB /app/serviceB
USER 65532:65532
ENTRYPOINT ["/app/serviceB"]
